[tool.poetry]
name = "django"
version = "50.0.0"
description = ""
authors = ["Dave Gaeddert <dave.gaeddert@gmail.com>", "Past authors of Django"]
# readme = "README.md"

packages = [
    { include = "django" },
    { include = "bolt" },
]

[tool.poetry.scripts]
bolt = "bolt.cli:cli"

[tool.poetry.dependencies]
python = "^3.10"
sqlparse = ">=0.3.1"
jinja2 = "^3.1.2"
python-dotenv = "^1.0.0"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
