[project]
name = "plain.start"
version = "0.2.2"
description = "Bootstrap a new Plain project from starter templates"
authors = [{ name = "Dave Gaeddert", email = "dave.gaeddert@dropseed.dev" }]
license = "BSD-3-Clause"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["click>=8.0.0"]

[project.scripts]
"plain-start" = "plain.start.cli:cli"

[tool.hatch.build.targets.wheel]
packages = ["plain"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
