[project]
name = "plain.pages"
version = "0.5.3"
description = "Simplified Markdown-based content for Plain."
authors = [{name = "Dave Gaeddert", email = "dave.gaeddert@dropseed.dev"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "plain<1.0.0",
    "mistune>=3.0.0",
    "python-frontmatter>=1.0.0",
    "pygments>=2.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["plain"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
