[project]
name = "plain.htmx"
version = "0.16.2"
description = "Integrate HTMX with templates and views."
authors = [{ name = "Dave Gaeddert", email = "dave.gaeddert@dropseed.dev" }]
license = "BSD-3-Clause"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["plain<1.0.0"]

[dependency-groups]
dev = ["plain.pytest<1.0.0"]

[tool.hatch.build.targets.wheel]
packages = ["plain"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
