[project]
name = "plain.scan"
version = "0.3.1"
description = "Remotely test for production best practices."
authors = [{name = "Dave Gaeddert", email = "dave.gaeddert@dropseed.dev"}]
readme = "README.md"
license = "BSD-3-Clause"
requires-python = ">=3.13"
dependencies = [
    "plain<1.0.0",
    "requests",
]

[project.scripts]
plain-scan = "plain.scan.cli:cli"

[project.entry-points."plain.setup"]
"scan-setup" = "plain.scan.entrypoints:setup"

[dependency-groups]
dev = [
    "plain.pytest<1.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["plain"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
